export const commentsData = [
  {
    id: 1,
    user: "Cục súc",
    avatar: "/images/avatars/pack6/02.jpg",
    gender: "male",
    rank: "free",
    text: "T nói nhé, tụi yêu nước online ko xem đc thì CÚT, bọn mày ko xem thì để người khác xem mắc mớ gì vào kêu gào gỡ bỏ phim?",
    up: 1,
    down: 1,
    replies: 14,
    movie: "Thủy Long Ngâm",
    poster:
      "https://static.nutscdn.com/vimg/300-0/6946fb51134899d6f8b1f0385e72638b.jpg",
  },
  {
    id: 2,
    user: "Hihi 🌷🫶🏻",
    avatar: "/images/avatars/pack6/08.jpg",
    gender: "female",
    rank: "free",
    text: "Sau màn tiêu diệt sát thủ Thập tam lâu tại Chùa Keo - Thái Bình ở tập 5, Thủy Long Ngâm - Tập 8 đưa chúng ta đến màn phóng hoả cực đỉnh!",
    up: 1,
    down: 0,
    replies: 11,
    movie: "Thủy Long Ngâm",
    poster:
      "https://static.nutscdn.com/vimg/300-0/6946fb51134899d6f8b1f0385e72638b.jpg",
  },
  {
    id: 3,
    user: "Naaunau.ne",
    avatar: "/images/avatars/pack1/25.jpg",
    gender: "male",
    rank: "free",
    text: "Coi tập 8 xong phải 'ồ quao' lên vì phim có chiều sâu và thông điệp rất mạnh về nữ quyền.",
    up: 6,
    down: 0,
    replies: 0,
    movie: "Gia Đình Bão Tố",
    poster:
      "https://static.nutscdn.com/vimg/300-0/38c8329b9ba9387c5cece8f0b4f7d7bc.jpg",
  },
  {
    id: 4,
    user: "Gnart",
    avatar: "/images/avatars/pack1/39.jpg",
    gender: "male",
    rank: "free",
    text: "Phim hay mà phục trang tệ quá. Nữ chính quê mùa thật sự, không hiểu sao stylist duyệt luôn 😭",
    up: 2,
    down: 0,
    replies: 3,
    movie: "Hãy Lấy Em Đi",
    poster:
      "https://static.nutscdn.com/vimg/300-0/fbd89fe595f9ca490cd41080cdd67fb3.jpg",
  },
  {
    id: 5,
    user: "Cô 2 Rổ",
    avatar:
      "https://u-static.nutscdn.com/vuresource/200-0/6e1e9e9c9833dd5920c2832df8f7a9b7.webp",
    gender: "female",
    rank: "admin",
    text: "Đã có trên web và fix xong sub lệch nha tụi e ❤️",
    up: 5,
    down: 0,
    replies: 0,
    movie: "Trò Chơi Dối Trá",
    poster:
      "https://static.nutscdn.com/vimg/300-0/aa33a22e91ee2f80321f7725f51755f3.jpg",
  },
  {
    id: 6,
    user: "Tí Còi",
    avatar: "/images/avatars/pack2/12.jpg",
    gender: "male",
    rank: "vip",
    text: "Nội dung chặt chẽ, diễn viên diễn tự nhiên. Nhưng nhạc phim hơi bị over 😅",
    up: 3,
    down: 1,
    replies: 2,
    movie: "Người Hùng Không Tên",
    poster:
      "https://static.nutscdn.com/vimg/300-0/6b6d1f3e74a5876c48d53b89d9c444ad.jpg",
  },
  {
    id: 7,
    user: "Miu Miu",
    avatar: "/images/avatars/pack3/05.jpg",
    gender: "female",
    rank: "free",
    text: "Phim xem chill lắm, cảnh đẹp mà màu phim cũng nhẹ nhàng, thích hợp cuối tuần ❤️",
    up: 10,
    down: 0,
    replies: 1,
    movie: "Một Ngày Nắng",
    poster:
      "https://static.nutscdn.com/vimg/300-0/fb126b12cbd9d5c799be54c5ddaf8a45.jpg",
  },
  {
    id: 8,
    user: "Miu Miu",
    avatar: "/images/avatars/pack3/05.jpg",
    gender: "female",
    rank: "free",
    text: "Phim xem chill lắm, cảnh đẹp mà màu phim cũng nhẹ nhàng, thích hợp cuối tuần ❤️",
    up: 10,
    down: 0,
    replies: 1,
    movie: "Một Ngày Nắng",
    poster:
      "https://static.nutscdn.com/vimg/300-0/fb126b12cbd9d5c799be54c5ddaf8a45.jpg",
  },
  {
    id: 9,
    user: "Miu Miu",
    avatar: "/images/avatars/pack3/05.jpg",
    gender: "female",
    rank: "free",
    text: "Phim xem chill lắm, cảnh đẹp mà màu phim cũng nhẹ nhàng, thích hợp cuối tuần ❤️",
    up: 10,
    down: 0,
    replies: 1,
    movie: "Một Ngày Nắng",
    poster:
      "https://static.nutscdn.com/vimg/300-0/fb126b12cbd9d5c799be54c5ddaf8a45.jpg",
  },
];
